version: '3.8'

services:
  anythingllm:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: anythingllm-prod
    ports:
      - "3001:3001"
    volumes:
      - ./server/storage:/app/server/storage
      - ./collector/hotdir:/app/collector/hotdir
      - ./collector/outputs:/app/collector/outputs
      - ./.env.production:/app/server/.env
    environment:
      - STORAGE_DIR=/app/server/storage
      - SERVER_PORT=3001
      - NODE_ENV=production
      - DOMAIN=llm.belltpo.com
      - HTTPS=true
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    depends_on:
      - prechat-widget
    networks:
      - anythingllm-network

  prechat-widget:
    build:
      context: ./prechat_widget
      dockerfile: Dockerfile
    container_name: prechat-widget-prod
    ports:
      - "9000:9000"
    volumes:
      - ./prechat_widget:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=prechat_widget.settings
      - ALLOWED_HOSTS=llm.belltpo.com,localhost
      - DOMAIN=llm.belltpo.com
    restart: unless-stopped
    networks:
      - anythingllm-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/var/www/static
    depends_on:
      - anythingllm
      - prechat-widget
    restart: unless-stopped
    networks:
      - anythingllm-network

networks:
  anythingllm-network:
    driver: bridge
