# Generated by Django 5.2.4 on 2025-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prechat', '0002_auto_20250821_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='prechatsubmission',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prechatsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prechatsubmission',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='prechatsubmission',
            table='prechat_submissions',
        ),
    ]
