# Generated by Django 5.2.4 on 2025-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prechat', '0004_chatconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prechatsubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
